# Generated by Django 2.1.2 on 2020-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20200719_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='title',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
