# Generated by Django 2.1.2 on 2020-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_timer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
